### ISSUE TITLE
dustjs custom helpers

### ISSUE THREAD

**Issue by killanaca** [wombatsecurity/dust-loader-complete#10]
Hi

first of all, thanks for the webpack loader

it's possibile to insert into the flow a custom dustjs helpers before the loader compile the template?

My configuration is:
webpack config 

```js
{ test: /\.dust$/, loader: 'dust-loader-complete', exclude: /node_modules/, query: { verbose: true } },
```

in my module file i have

```js
const tmpl = require('template.dust');
```

but in my template i have a custom dustjs helper formatDate that is defined in a separate file
dustjs-custom-helpers.js

```js
const dust = require('dustjs-linkedin');
dust.helpers.formatDate = function formatDate(chunk, context, bodies, params) {
....
}
```

**Comment by jrrbru** [comment]
Hi Killanaca,

Thanks for checking out the loader!

We don't currently have a mechanism for automatically inserting a helpers file into the bundle. What you can do is simply `require('dustjs-custom-helpers')` from your main entry point. Webpack is smart enough to only include one `dustjs-linkedin` module, and because DustJS is global in the browser, your helpers will work in your templates. Give it a shot and let me know if it works out for you.

I think it would be cleaner to have a way of specifying helper modules, so I think we will consider that for a future enhancement.

**Comment by killanaca** [comment]
Hi 
i tried to add the `require('dustjs-helpers');` to my main entry point, but webpack tells me
`
ERROR in ./~/dustjs-helpers/lib/dust-helpers.js
Module not found: Error: Cannot resolve module 'dust.core' in E:\P\14\DW\...
 @ ./~/dustjs-helpers/lib/dust-helpers.js 3:4-34
`

**Comment by killfish** [comment]
I didn't need UMD support so I just removed AMD from the module factory

`(function(root, factory) {
  if (typeof exports === 'object') {
    module.exports = factory(require('dustjs-linkedin'));
  } else {
    factory(root.dust);
  }
}(this, function(dust) {`

vs.

`(function(root, factory) {
  if (typeof define === 'function' && define.amd && define.amd.dust === true) {
    define(['dust.core'], factory);
  } else if (typeof exports === 'object') {
    module.exports = factory(require('dustjs-linkedin'));
  } else {
    factory(root.dust);
  }
}(this, function(dust) {`

**Comment by killanaca** [comment]
@killfish i make the same workaround but the problem is that i must do the same workaround every time someone download our project and make npm install on it

**Comment by jrrbru** [comment]
@killanaca & @killfish, I'm fixing that by adding dust.core to the alias section of the webpack.config:
```javascript
alias: {
  ....
  "dust.core": "dustjs-linkedin"
}
```
That lets webpack find dustjs-linkedin by aliasing it to dust.core. I'll add a note to the README for any others who might need it.

**Comment by killanaca** [comment]
it's works. thanks a lot

**Comment by jrrbru** [comment]
No problem!
