### ISSUE TITLE
chk.w is not a function(…)

### ISSUE THREAD

**Issue by alexwasner** [wombatsecurity/dust-loader-complete#12]
I'm trying to integrate this into (Lavaca)[https://github.com/mutualmobile/lavaca-starter/] and am running into an issue when attempting to render a file. I get `chk.w is not a function(…)` when calling `template({...},callback...);`. 

Can you think of anything to try? Here is the test template I am using after it has been parsed by webpack.

```var dust = __webpack_require__(43); (function(dust){dust.register("src\/www\/js\/templates\/pageviews\/home.html",body_0);function body_0(chk,ctx){return chk.w("<h1>").f(ctx.getPath(false, ["messages","headline"]),ctx,"h").w("</h1>");}body_0.__dustBody=!0;return body_0}(dust));var fn = function( context, callback ) { dust.render( 'src/www/js/templates/pageviews/home.html', context, callback ); }; fn.templateName = "src/www/js/templates/pageviews/home.html"; module.exports = fn;```

**Comment by jrrbru** [comment]
Thanks for commenting, Alex. Can you post the dust code (pre-compilation) as well so I can take a look at it?

**Comment by alexwasner** [comment]
Its a simple template. `<h1>{messages.headline}</h1>`

**Comment by jrrbru** [comment]
Yes, that is pretty simple.

The error might be in how you are trying to render the template. The loader returns a function that receives a `context` object and a callback. So you would use it like this:
```javascript
var template = require( 'my/template/here' );
template( { foo: 'bar' }, function( err, out ) {
  // out is the output of the template
} );
```
Is that how you are rendering the template?

**Comment by alexwasner** [comment]
Yep, tried that. I pushed the broken code to a separate branch on my repo (https://github.com/mutualmobile/lavaca-starter/tree/webpack-starter) if you wanted to see exactly what I'm doing. If you pull that and run `npm install -g bower` + `npm install` + `bower isntall` + `grunt`,  you should be able to replicate it on `localhost:3000`

**Comment by alexwasner** [comment]
Some more information that might help, if I manually type in the browser console  `dust.cache["src/www/js/templates/pageviews/ahomeb"] = 
function body_0(chk,ctx){return chk.write("<h1>").section(ctx.getPath(false, ["messages","headline"]),ctx,"h").write("</h1>");}` and then run `dust.render('src/www/js/templates/pageviews/ahomeb',{ },function...)', it successfully outputs the right string. Notice, what I typed in does not have the shorthand `.w().f().w()` syntax.

**Comment by jrrbru** [comment]
I pulled the branch and ran it, but I'm getting a different error - it looks like Lavaca is trying to `require( '$' )`, which isn't defined. You might need to add an alias for jquery in your weback config.

![jquery missing](https://cloud.githubusercontent.com/assets/3642032/12816726/0e610850-cb1c-11e5-8ea7-56169c4c37d5.png)

**Comment by alexwasner** [comment]
Hmm. Its aliased for me with `'jquery': 'jquery/jquery.min.js',`. Are you sure `bower install` successfully pulled 2.0.3 of jqeury to `/src/www/components`?

**Comment by jrrbru** [comment]
Yes, jquery is there. But the source in `src\www\components\lavaca\src\mvc\View.js` isn't requiring `jquery`, it's requiring `$`, and unless you tell webpack to alias `'$': 'jquery/jquery.min.js'`, it won't know what `$` is.

I take it you aren't getting that error, but I don't understand why that would be.

**Comment by alexwasner** [comment]
`https://github.com/mutualmobile/lavaca/blob/webpack/src/mvc/View.js` shows that its requiring `jquery` instead of `$`. Are you sure you pulled the right branch? Does your bower.json say `"lavaca": "mutualmobile/lavaca#webpack",` on `line 17`

**Comment by alexwasner** [comment]
I think I had two conflicting versions of dust somehow. I'm gonna go ahead and close this. THanks for looking into it.

**Comment by jrrbru** [comment]
No problem.

**Comment by mailingmuthu** [comment]
@alexwasner 
HI Alex, Is there any solution to resolve issue chk.w() is not a function. I'm also facing the same issue.

**Comment by jrrbru** [comment]
Hi @mailingmuthu. If you can post a link to your code, I could take a look at it.

**Comment by mailingmuthu** [comment]
@jrrbru  I was trying to Update dustJs version as follows: then it starts throwing error as shown below. the case is similar to what alex has mentioned.

** @From:**
"dustjs-helpers": "~1.3.0",
"dustjs-linkedin": "~2.4.2",
"engine-munger": "^0.2.0",

**Update To:**
"dusthelpers-supplement": "~0.0.4",
"dustjs-helpers": "~1.6.0",
"dustjs-linkedin": "~2.6.0",
"engine-munger": "^0.2”,

**Error Details:** 
Uncaught TypeError: chk.w is not a function
    at Object.body_0 [as api] (https://localhost:8443/templates/US/en/api.js?r=cb26f31beaa8582bc4908c5f53a7aad687dfdaee:1:81)
    at https://localhost:8443/components/dustjs-linkedin/dist/dust-full.min.js?r=cb26f31beaa8582bc4908c5f53a7aad687dfdaee:4:2495body_0 @ api.js?r=cb26f31…:1(anonymous function) @ dust-full.min.js?r=cb26f31…:4

(function(dust){dust.register("api",body_0);function body_0(chk,ctx){return chk.w("<div class=\
