### ISSUE TITLE
Export the compiled template instead of a wrapper function

### ISSUE THREAD

**Issue by chrisdothtml** [wombatsecurity/dust-loader-complete#16]
The wrapper function, while quicker, makes for code that could potentially be confusing to a new developer who is familiar with DustJS, but isn't familiar with webpack.

When a template is compiled, dust returns an object that can be passed into `dust.render`. This is what should be exported as the module.

For more info, see how [rollup-plugin-dustjs](https://github.com/chrisdothtml/rollup-plugin-dustjs#use) is used. Willing to PR if needed.

**Comment by jrrbru** [comment]
Hi Chris,

Thanks for creating the issue. I think you're right; this was initially created for use with [MarionetteJS](https://marionettejs.com/) and so some assumptions were made about usage that aren't necessarily universal. If you have time for a PR (or even a snippet to demonstrate an approach) that would hasten getting a fix in.

**Comment by chrisdothtml** [comment]
Great! I'll put together a PR in the next few days or so

**Comment by twhitbeck** [comment]
@chrisdothtml we've updated to `v3.0.0` which now defaults to exporting the compiled template.
