### ISSUE TITLE
Default dustAlias requires aliasing dustjs-linked

### ISSUE THREAD

**Issue by twhitbeck** [wombatsecurity/dust-loader-complete#20]
The default option for `dustAlias` is `dustjs`. This means that this loader can't be used out of the box without specifying either an alias in your webpack config for `dustjs-linked` or supplying the `dustAlias` option of `dustjs-linkedin`. Is there a reason the default isn't `dustjs-linkedin`?

**Comment by jrrbru** [comment]
Probably not a good reason. I guess before I publish 3.0.0 on npm, it would make sense to make this breaking change as well.

**Comment by jrrbru** [comment]
Fixed in referenced PR
