### ISSUE TITLE
Moving my code from grunt to webpack

### ISSUE THREAD

**Issue by rkrishn** [wombatsecurity/dust-loader-complete#31]
I am Having issue with dust loader complete which generates this kind of output in the below image but the exisiting code generated html string after compiling using grunt could you please let me know how do i get compiled html code using dust loader ?
![screenshot from 2018-12-07 16-01-17](https://user-images.githubusercontent.com/16647331/49642782-f7aa1980-fa39-11e8-8c7b-d8f4ba9298a4.png)
![screenshot from 2018-12-07 16-02-25](https://user-images.githubusercontent.com/16647331/49642783-f842b000-fa39-11e8-9b59-6d8f4ed9239b.png)

**Comment by jrrbru** [comment]
Hi Ramakrishna, thanks for checking out the project. Can you share getPopupFormLayoutTemplate() with me? It looks to me like you are _returning_ the compiled template function, rather than _executing_ it. The way the loader works is that you compile the templates during the build process, and they are made available to the bundle as template functions. In order to get out the HTML, you need to execute those functions, passing in the context (the data to be used to in rendering the HTML).

**Comment by rkrishn** [comment]
Hi @jrrbru here are the functions
                 `
        
     getPopupFormLayoutTemplate: function (options) {
            return $('<div></div>').append(this.getPopupFormLayoutMarkup(options)).html();
        },

      getPopupFormLayoutMarkup: function (options) {
            var self = this,
                el = (options.el).trim(),
                $el = $(el),
                $formAttributes = $el.find([data-attribute]).eq(0).parent();
            if ($el.has('.js-inline-create-form-body').length) {
                $formAttributes = $el.find('.js-inline-create-form-body');
            }

            TemplateHelper.compile(PopupFormTemplate, 'popup-form');

            var $popupForm = $(TemplateHelper.renderedOutput('popup-form', {
                title: options.title,
                saveButtonClassName: options.saveButtonClassName
            }));
            if($popupForm.find('.popup-body').find('.error_el').length <= 0){
            	$popupForm.find('.popup-body').append('<div class="error_el"></div>');
            }
            $popupForm.find('.popup-body').append($formAttributes.html());

            $popupForm.delegate('[data-dismiss="popup"]', 'click', function (event) {
                self.removeLayer($(this).parents('.overlay-bg'));
            });

            return $popupForm;
        }

` 

i am getting error on this line  el = (options.el).trim(),  because the template is not a html string.

**Comment by rkrishn** [comment]
is it possible to build dust files and return only html strings to bundle js as in our existing code we dont include dust files in production all the files are precompiled to html strings

**Comment by jrrbru** [comment]
Not with dust-loader-complete. It's really not how dust is meant to be used. I'm also not sure how you would get any client-side variables/data into your template that way. And if you aren't using client-side variables/data, then you should really just write static HTML.

**Comment by jrrbru** [comment]
Just as an example, you are doing this:
```
    var $popupForm = $(TemplateHelper.renderedOutput('popup-form', {
      title: options.title,
      saveButtonClassName: options.saveButtonClassName
    }));
```
The normal way to use dustjs would be to include dust.core in your webpack bundle, then pass your "options" as context data to the dust.render method:
```
let html;
dust.render( lefTemplatesForm, {
    saveButtonClassName: "foo",
    title: "bar",
  }, 
  function( err, out ) {
    if ( err ) {
      // log errors here if you want
    } else {
      html = out;
    }
  } );
```

**Comment by rkrishn** [comment]
@jrrbru i tried the above code but i get output undefined attaching the screenshot please have a look

![screenshot from 2018-12-08 13-14-05](https://user-images.githubusercontent.com/16647331/49683463-567b9b80-faeb-11e8-9045-ddf0deb94505.png)

**Comment by rkrishn** [comment]
@jrrbru i got it working i had some issue with jquery i18 not detecting in dust files however i have one more issue i am getting dust.compile undefined how do i include dust core in the bundle what is the webpack configuration for that ?
![screenshot from 2018-12-11 12-24-59](https://user-images.githubusercontent.com/16647331/49783516-0e08eb80-fd40-11e8-9211-50b6436a3d01.png)

**Comment by rkrishn** [comment]
i am having this issue
https://github.com/linkedin/dustjs/issues/766

**Comment by jrrbru** [comment]
I don't know what file your screenshots are from, but the way the loader is meant to be used with dust is that the loader itself calls `dust.compile()`. So you shouldn't need `dust.compile()` in the bundle, because you don't run in the browser.

**Comment by rkrishn** [comment]
hmm i think my code is bit old and its not compatible with node module dust library with webpack. @jrrbru thanks a lot for the responses you can close this issue.
